version: "3.5"

services:
    frontend:
        build: ./node
        container_name: frontend
        ports:
            - target: 3000
              published: 3000
        networks: 
            - node-spring
    backend:
        build: ./spring
        container_name: backend
        ports:
            - target: 8080
              published: 8080
        networks: 
            - spring-mongo
            - node-spring
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - target: 27017
              published: 27017
        volumes:
            - type: volume
              source: mongodb_vol
              target: /data/db
        networks: 
            - spring-mongo

volumes:
    mongodb_vol: 
networks: 
    spring-mongo:
    node-spring:
    