version: "3.5"

services:
    frontend:
        build: ./node
        container_name: frontend
        ports:
            - "3000:3000"
        networks: 
            - node-spring
            - node-mq
        environment:
            HOST: backend
            MQ: rabbitmq
        depends_on: 
            - backend
            - rabbitmq
    backend:
        build: ./spring
        container_name: backend
        expose:
            - "8080"
        networks: 
            - spring-mongo
            - node-spring
    mongodb:
        image: mongo:latest
        container_name: mongodb
        expose:
            - "27017"
        volumes:
            - type: volume
              source: mongodb_vol
              target: /data/db
        networks: 
            - spring-mongo
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        expose:
            - "5672"
            - "15672"
        networks: 
            - node-mq
            - mq-logger
    logger:
        build: ./python-logging
        container_name: logger
        environment:
            HOST: rabbitmq
        networks:
            - mq-logger
volumes:
    mongodb_vol: 
networks: 
    spring-mongo:
    node-spring:
    node-mq:
    mq-logger:

    