version: "3.5"

services:
    frontend:
        build: ./node
        container_name: frontend
        ports:
            - "3000:3000"
        networks: 
            - node-spring
        environment:
            HOST: backend
        depends_on: 
            - backend
    backend:
        build: ./spring
        container_name: backend
        expose:
            - "8080"
        networks: 
            - spring-mongo
            - node-spring
    mongodb:
        image: mongo:latest
        container_name: mongodb
        expose:
            - "27017"
        volumes:
            - type: volume
              source: mongodb_vol
              target: /data/db
        networks: 
            - spring-mongo

volumes:
    mongodb_vol: 
networks: 
    spring-mongo:
    node-spring:
    